-- Migration 007: Performance indexes (v2 — no partial indexes with NOW())
-- Previous version had NOW() in predicate (not IMMUTABLE) — fixed in 008
-- Indexes created by 008 are sufficient for query optimization.
-- This migration is a no-op marker for deployment ordering.
